2025-06-11 14:13:13,647 INFO    MainThread:691226 [internal.py:wandb_internal():90] W&B internal server running at pid: 691226, started at: 2025-06-11 14:13:13.647164
2025-06-11 14:13:13,650 DEBUG   HandlerThread:691226 [handler.py:handle_request():141] handle_request: run_start
2025-06-11 14:13:13,650 INFO    WriterThread:691226 [datastore.py:open_for_write():75] open: /data2/xxw_data/projects/LLM/Diffusive-Latent-CoT/wandb/offline-run-20250611_141313-sud3h74c/run-sud3h74c.wandb
2025-06-11 14:13:13,667 DEBUG   HandlerThread:691226 [meta.py:__init__():35] meta init
2025-06-11 14:13:13,667 DEBUG   HandlerThread:691226 [meta.py:__init__():49] meta init done
2025-06-11 14:13:13,667 DEBUG   HandlerThread:691226 [meta.py:probe():209] probe
2025-06-11 14:13:13,676 DEBUG   HandlerThread:691226 [meta.py:_setup_git():199] setup git
2025-06-11 14:13:13,684 DEBUG   HandlerThread:691226 [meta.py:_setup_git():206] setup git done
2025-06-11 14:13:13,685 DEBUG   HandlerThread:691226 [meta.py:_save_pip():53] save pip
2025-06-11 14:13:13,685 DEBUG   HandlerThread:691226 [meta.py:_save_pip():67] save pip done
2025-06-11 14:13:13,685 DEBUG   HandlerThread:691226 [meta.py:_save_conda():74] save conda
2025-06-11 14:13:16,637 DEBUG   HandlerThread:691226 [meta.py:_save_conda():84] save conda done
2025-06-11 14:13:16,637 DEBUG   HandlerThread:691226 [meta.py:probe():247] probe done
2025-06-11 14:14:38,715 DEBUG   HandlerThread:691226 [handler.py:handle_request():141] handle_request: partial_history
2025-06-11 14:15:08,005 DEBUG   HandlerThread:691226 [handler.py:handle_request():141] handle_request: partial_history
2025-06-11 14:15:28,001 WARNING MainThread:691226 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-06-11 14:15:28,177 WARNING MainThread:691226 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-06-11 14:15:28,177 ERROR   MainThread:691226 [internal.py:wandb_internal():156] Internal process interrupted.
2025-06-11 14:15:28,671 INFO    SenderThread:691226 [sender.py:finish():1111] shutting down sender
2025-06-11 14:15:28,691 INFO    MainThread:691226 [internal.py:handle_exit():80] Internal process exited
