2025-06-15 06:20:47,070 INFO    MainThread:1234213 [internal.py:wandb_internal():90] W&B internal server running at pid: 1234213, started at: 2025-06-15 06:20:47.070234
2025-06-15 06:20:47,073 INFO    WriterThread:1234213 [datastore.py:open_for_write():75] open: /data2/xxw_data/projects/LLM/Diffusive-Latent-CoT/wandb/offline-run-20250615_062046-4l378v26/run-4l378v26.wandb
2025-06-15 06:20:47,074 DEBUG   HandlerThread:1234213 [handler.py:handle_request():141] handle_request: run_start
2025-06-15 06:20:47,092 DEBUG   HandlerThread:1234213 [meta.py:__init__():35] meta init
2025-06-15 06:20:47,092 DEBUG   HandlerThread:1234213 [meta.py:__init__():49] meta init done
2025-06-15 06:20:47,092 DEBUG   HandlerThread:1234213 [meta.py:probe():209] probe
2025-06-15 06:20:47,102 DEBUG   HandlerThread:1234213 [meta.py:_setup_git():199] setup git
2025-06-15 06:20:47,111 DEBUG   HandlerThread:1234213 [meta.py:_setup_git():206] setup git done
2025-06-15 06:20:47,111 DEBUG   HandlerThread:1234213 [meta.py:_save_pip():53] save pip
2025-06-15 06:20:47,111 DEBUG   HandlerThread:1234213 [meta.py:_save_pip():67] save pip done
2025-06-15 06:20:47,112 DEBUG   HandlerThread:1234213 [meta.py:_save_conda():74] save conda
2025-06-15 06:20:51,098 DEBUG   HandlerThread:1234213 [meta.py:_save_conda():84] save conda done
2025-06-15 06:20:51,098 DEBUG   HandlerThread:1234213 [meta.py:probe():247] probe done
2025-06-15 06:21:00,951 WARNING MainThread:1234213 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-06-15 06:21:01,102 WARNING MainThread:1234213 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-06-15 06:21:01,102 ERROR   MainThread:1234213 [internal.py:wandb_internal():156] Internal process interrupted.
2025-06-15 06:21:01,374 INFO    MainThread:1234213 [internal.py:handle_exit():80] Internal process exited
