2025-06-12 02:22:10,781 INFO    MainThread:2196942 [internal.py:wandb_internal():90] W&B internal server running at pid: 2196942, started at: 2025-06-12 02:22:10.780776
2025-06-12 02:22:10,783 INFO    WriterThread:2196942 [datastore.py:open_for_write():75] open: /data2/xxw_data/projects/LLM/Diffusive-Latent-CoT/wandb/offline-run-20250612_022210-teurmljh/run-teurmljh.wandb
2025-06-12 02:22:10,783 DEBUG   HandlerThread:2196942 [handler.py:handle_request():141] handle_request: run_start
2025-06-12 02:22:10,798 DEBUG   HandlerThread:2196942 [meta.py:__init__():35] meta init
2025-06-12 02:22:10,798 DEBUG   HandlerThread:2196942 [meta.py:__init__():49] meta init done
2025-06-12 02:22:10,798 DEBUG   HandlerThread:2196942 [meta.py:probe():209] probe
2025-06-12 02:22:10,807 DEBUG   HandlerThread:2196942 [meta.py:_setup_git():199] setup git
2025-06-12 02:22:10,814 DEBUG   HandlerThread:2196942 [meta.py:_setup_git():206] setup git done
2025-06-12 02:22:10,814 DEBUG   HandlerThread:2196942 [meta.py:_save_pip():53] save pip
2025-06-12 02:22:10,814 DEBUG   HandlerThread:2196942 [meta.py:_save_pip():67] save pip done
2025-06-12 02:22:10,815 DEBUG   HandlerThread:2196942 [meta.py:_save_conda():74] save conda
2025-06-12 02:22:13,636 DEBUG   HandlerThread:2196942 [meta.py:_save_conda():84] save conda done
2025-06-12 02:22:13,637 DEBUG   HandlerThread:2196942 [meta.py:probe():247] probe done
2025-06-12 02:30:02,934 WARNING MainThread:2196942 [internal.py:wandb_internal():153] Internal process interrupt: 1
2025-06-12 02:30:03,200 WARNING MainThread:2196942 [internal.py:wandb_internal():153] Internal process interrupt: 2
2025-06-12 02:30:03,200 ERROR   MainThread:2196942 [internal.py:wandb_internal():156] Internal process interrupted.
2025-06-12 02:30:03,358 INFO    WriterThread:2196942 [datastore.py:close():279] close: /data2/xxw_data/projects/LLM/Diffusive-Latent-CoT/wandb/offline-run-20250612_022210-teurmljh/run-teurmljh.wandb
2025-06-12 02:30:03,372 INFO    HandlerThread:2196942 [handler.py:finish():806] shutting down handler
2025-06-12 02:30:03,414 INFO    MainThread:2196942 [internal.py:handle_exit():80] Internal process exited
